### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [kjinho/ciao#3]
Building with SBCL 2.3.11.165-7fa632585 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 2f2b0acc81ae45204d30bf4d803244d8f980522e

*ciao* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: end of file on #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/ciao/ab6e1ade9914b8d098b0f80b1af65f18bcc19ce0/ciao-20240402-git/src/ciao.lisp" {101396BCF3}>(in form starting at line: 134, column: 0, position: 3736)
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD tid=526523 "main thread" RUNNING {10017D8003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "ciao" "src" "ciao">

```

*ciao/tests* fails to build because of a failure in  _ciao_.

[Full log here](http://report.quicklisp.org/2024-04-01/failure-report/ciao.html)

**Comment by kjinho** [comment]
Bug introduced in #2. Should be fixed in 80f14ac/
